### PR TITLE
changed SHOCK upload in unit tests to DataFileUtil.file_to_shock()

### PR DESCRIPTION
**Pull request by Yzm1234**

### CODE REVIEW

**Comment by dcchivian** [comment]
@jsfillman It looks like this module isn't getting the most up-to-date token in test.cfg.  Can you please take a look?  Thanks!

**Comment by sychan** [comment]
@dcchivian This module doesn't appear to have a test token setup. For the tests, who's account is needed, or will any old KBase account work?

**Comment by dcchivian** [comment]
@sychan the test tokens are set up by @jsfillman .  I don't know the mechanism.

**Comment by dakotablair** [comment]
See PR #29.

**Pull request closed without merging**
